name: CI

# Definindo quando as ações devem ser executadas
on:
  # Gatilho para o workflow quando uma requisição "push" é feita no branch principal
  push:
    branches: [ main ]

# Criando o workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # O tipo de runner onde o job será executado
    runs-on: ubuntu-latest

    # Passos a serem exeutados na tarefa
    steps:
      # Fazendo o check-out do repositório com o $GITHUB_WORKSPACE, para a tarefa poder acessá-lo
      - uses: actions/checkout@v2
      
      # Configurando o ambiente do Node.js com a versão apropriada
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      
      # Instalando as dependências com o NPM/Yarn
      - name: Install dependencies
        run: yarn
      
      # Executando a build
      - name: Run Build
        run: yarn build
      
      # Copiar o repositório para o diretório no servidor/VPS utilizado para a aplicação
      - name: Copy dist to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Selecionando todas as pastas com exceção do "node_modules"
          source: ".,!node_modules"
          # O caminho é baseado no diretório onde o usuário logado no servidor inicia
          target: "~/app/gobarber-backend"
      
      # Executar "yarn" no servidor
      - name: Instal dependencies on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Definindo os comandos a serem executados
          script: |
            cd ~/app/gobarber-backend
            yarn
          
      # Executar as migrations do TypeORM
      - name: Run migrations on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Definindo os comandos a serem executados
          script: |
            cd ~/app/gobarber-backend
            ./node_modules/.bin/typeorm migration:run
            
      # Restart no servidor Node.js
      - name: Restart Node server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Definindo os comandos a serem executados
          script: pm2 restart gobarber-api
